apiVersion: 1

datasources:
  - name: ${DS_PROMETHEUS}
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Must match the Docker service name and port of the Prometheus deployment
    isDefault: true
    editable: false
    jsonData:
      timeInterval: "10s"
